### ISSUE TITLE
SimpleGraFix seemingly missing from loens2.spdns.de/mamong_us/repos/

### ISSUE THREAD

**Issue by TerletPaper** [Q11Maristenkolleg/Mamong-us-java#14]
"Failed to execute goal on project Mamong-Us: Could not resolve dependencies for project tk.mamong_us:Mamong-Us:jar:1.6.5-alpha: Failed to collect dependencies at com.siinus:SimpleGraFix:jar:1.4: Failed to read artifact descriptor for com.siinus:SimpleGraFix:jar:1.4: Could not transfer artifact com.siinus:SimpleGraFix:pom:1.4 from/to mamong-us-repository (https://loens2.spdns.de/mamong_us/repos/): Transfer failed for https://loens2.spdns.de/mamong_us/repos/com/siinus/SimpleGraFix/1.4/SimpleGraFix-1.4.pom: Unknown host loens2.spdns.de -> [Help 1]"

**Comment by FauxKiwi** [comment]
The host has been moved to loens2.com
You can either fix it yourself and create a pull request or I'll update it tomorrow
